version: '3.8'

services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: microservice
    volumes:
      - ./data:/data/db

  microservicesproject:
    build: .
    container_name: microservicesproject
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:1234@mongodb:27017/microservice?authSource=admin
    depends_on:
      - mongodb
